### ISSUE TITLE
Bug [NameError: name 'raw_input' is not defined]

### ISSUE THREAD

**Issue by Rhgxz7** [lowerednonce/60lminesweeper#1]
When runnig main.py program crashes with error:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\60lminesweeper-main\main.py", line 40, in <module>
    displaymap(False);c=raw_input(">").split(" ")
                        ^^^^^^^^^
**NameError:** name 'raw_input' is not defined

**Python version:** Python 3.11.2
**OS:** Windows 11 64bit

**Comment by meta-monad** [comment]
Thank you for your issue. The codebase is written in python2 and uses *raw_input* instead of *input* because the latter causes issues with parsing. However, it has been a while since I wrote the code so I cannot tell exact details.
